config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home', as: 'pages_home'
  get 'pages/posts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def posts
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div>
  <p class="title">Agenda</p>

  <table class="table is-striped is-hoverable is-fullwidth">
    <tfoot>
      <tr>
        <td colspan="3">
          <%= link_to 'New event', new_event_path %>
        </td>
      </tr>
    </tfoot>
    <tbody>
      <% @events.order(:date).each do |event| %>
        <tr>
          <td>
            <%= l event.date %>
          </td>
          <td>
            <%= event.title %>
          </td>
          <td>
            <%= truncate(strip_tags(event.description), length: 80) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'partials/banner' %>
<%= render 'partials/posts' %>
<%= render 'partials/agenda' %>

app/views/pages/posts.html.erb
<br><br><br><br>
<p class="title is-2 has-text-centered">Les actualités</p>
<div class="is-ancestor">
    <% Post.order(date: :desc).each_with_index do |post,index| %>
        <% if index % 4 == 0 %>
            <div class="tile mx-5">
            <%= render partial: 'partials/post_tile', locals: { post: post } %>
        
        <% elsif index % 4 == 3 %>
            <%= render partial: 'partials/post_tile', locals: { post: post } %>
            </div>
        
        <% else %>
            <%= render partial: 'partials/post_tile', locals: { post: post } %>
        <% end %>
    <% end %>
</div>

// TODO
<!-- 
boucler for(i=0 ; i<4 ; i++){
    parcourir Post{
        créer une div "tile is-ancestor is-vertical is-gapless mx-5"
            tous les modulo 4=i{
                render partial
            }
        </div>
    }
}
-->

app/views/partials/_agenda.html.erb
<div class="columns is-mobile">
    <div class="column is-half is-offset-one-quarter">
        <p class="title is-2 has-text-centered">Agenda</p>

        <table>
            <tbody>
            <% Event.order(:date).limit(3).each do |event| %>
                <tr class="box tr-border">
                    <td class="subtitle is-7 has-text-weight-normal">
                        <p><%= event.date.day %></p>
                        <p><%= l event.date, format: :month %></p>
                        <p><%= event.date.year %></p>
                    </td>
                    <td>
                        <p class="title is-4"><%= event.title %></p>
                        <p class="content"><%= truncate(strip_tags(event.description), length: 120) %></p>
                        <a href="#" class="content is-danger has-text-centered">Lire la suite...</a>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/partials/_banner.html.erb
<section class="hero is-fullheight">
  <div class="hero-body hero-background">
    <div class="column is-half ml-6">
      <p class="title is-1 mb-6">
        Bienvenue sur le site du Réseau National des Maisons des Associations
      </p>
      <p class="subtitle">
        Retrouver sur ce site tout ce qui est en lien avec le Réseau National des Maisons des Associations
      </p>
    </div>
    <div class="column ml-7">
      <figure>
        <%= image_tag "logo.png" %>
      </figure>
    </div>
  </div>
</section>

app/views/partials/_footer.html.erb
<div class="footer">
    
</div>

app/views/partials/_nav.html.erb
<nav class="navbar is-fixed-top is-transparent" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href=<%= pages_home_path %>>
      <%= image_tag('logo.png') %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href=<%= pages_home_path %>>
        Accueil
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Au niveau national
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            Pourquoi des maisons des associations ?
          </a>
          <a class="navbar-item">
            Pourquoi un réseau ?
          </a>
          <a class="navbar-item">
            Agenda
          </a>
          <a class="navbar-item">
            Charte, statuts et règlement intérieur
          </a>
          <a class="navbar-item">
            Une longue histoire d'échanges...
          </a>
          <a class="navbar-item">
          Newsletter
          </a>
        </div>
      </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Dans les régions
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            Les membres du RNMA
          </a>
          <a class="navbar-item">
            Outils et compétences des Maisons des associations du réseau
          </a>
          <a class="navbar-item">
            Les sites internet des membres
          </a>
        </div>
      </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Nos ressources
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            Le repère
          </a>
          <a class="navbar-item">
            Rencontres nationales digitales du RNMA
          </a>
          <a class="navbar-item">
            Partage en période de COVID-19
          </a>
          <a class="navbar-item">
            Métier accompagnateur
          </a>
          <a class="navbar-item">
            Ressources de nos partenaires
          </a>
        </div>
      </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Nos actions
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            Observer pour agir
          </a>
          <a class="navbar-item">
            L'engagement à portée de tous
          </a>
          <a class="navbar-item">
            Soutien aux micro-employeurs associatifs
          </a>
          <a class="navbar-item">
            Soutien aux projets inter-associatifs
          </a>
          <a class="navbar-item">
            Formation et ingéniérie
          </a>
        </div>
      </div>

      <a class="navbar-item">
        Réseaux et partenaires
      </a>

      <a class="navbar-item">
        Liens
      </a>

      <a class="navbar-item">
        Contact
      </a>

      <a class="navbar-item">
        Demande d'infos
      </a>
    </div>
  </div>
  </nav>

app/views/partials/_post_card.html.erb
<div class="column is-one-third">
    <div class="card">
    
        <div class="card-image">
            <figure class="image is-256x256">
                <img src="https://www.santepubliquefrance.fr/var/site/storage/images/8/4/3/5/2755348-1-fre-FR/spf_dossier_covid_header.jpg" alt="Placeholder image">
                <div class="is-danger-image-hover">
            </figure>
        </div>
        <div class="card-content">
            <p class="title is-5 card-footer-border-top is-danger-text-hover has-text-centered"><%= post.title %></p>
            <!--<p class="subtitle is-7 has-text-weight-normal"><%= l post.date %></p>-->
            <div class="content">
                <p class="content has-text-centered "><%= truncate(strip_tags(post.description), length: 120) %></p>
            </div>
            
        </div>
        <footer class="card-footer">
            <a href="#" class="content card-footer-item is-danger has-text-centered">Lire la suite...</a>
        </footer>
    </div>
</div>

app/views/partials/_posts.html.erb
<div class="post">
  <p class="title is-2 mt-3 has-text-centered">À la une</p>
  <div class="columns mx-6">
        <% Post.order(date: :desc).limit(3).each do |post| %>
          <%= render partial: 'partials/post_card', locals: { post: post } %>
        <% end %>
  </div>

  <section class="hero is-link is-small">
    <div class="hero-body">
      <div class="container has-text-centered">
        <button class="button is-primary is-centered">
          <%= link_to 'Toutes les actualités', pages_posts_path %>
        </button>
      </div>
    </div>
  </section>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.date %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>